### ISSUE TITLE
ColonelKai's Roadmap 

### ISSUE THREAD

**Issue by ColonelKai** [koiboi-dev/MissileWarfare#20]
## 1.7 | Better Missiles Update
**1.7.1**
- [ ] Internal Code Refactors. 
- [ ] Add better missile cleanup for future radar implementation.
- [ ] Missile firing sequences changed.
- [ ] Missile types changed, splitting SSMs (surface-to-surface missile) into two categories; cruise and ballistic.

## 1.8 | Quality of Life Updates

**1.8.1**
- [ ] Change missile naming scheme, add new Surface-to-Air Missiles (SAM).
- [ ] Change ground-to-ground missile trajectory to give missile impacts some more oompf.
- [ ] Add missile sound effects for MORE OOMPF.

**1.8.2**
- [ ] Add IFF (Identification of Friend or Foe) IDs. These will replace the current playerIDs. They will work by assigning every launcher, radar and player an IFF. They will have books similar as to before, which will have an IFF-ID. You will be able to use the book to assign.
- [ ] Make sure SAMs cannot shoot down missiles wit hthe same IFF-ID as their launcher. Same goes with players and elytra launchers.

## 1.9 | Radar & SAM Updates

**1.9.1**
- [ ] Add Radar multiblocks. For search radars; They should have signs that display the direction and distance of missiles. IFF-Compatible. Optimisation is key. The radars range should be adjustable. For Tracking radars; They only work when they are connected to a search radar, and they lock onto a target picked up by the search radar, and keep the lock on for as long as possible.

**1.9.2**
- [ ] Add Player Search Radars. They will detect a player either with an elytra or in the line of sight. IFF-compatible. Can relay to tracking radar.

**1.9.3**
- [ ] Make SAMs require a radar. They radar will ping nearby (distance depending on the radar model) SAM launchers with the same IFF-ID, and if they have a missile that has the range, it will shoot them down.

**1.9.4**
- [ ] Add Anti-Radiation Missiles. Basically, after being thrown into the air, it will travel to its destination like a normal rocket. However, if it finds a radar on its way there, it will lock onto it instead, and attempt to destroy it.
- [ ] [OPTIONAL] Add jammers. I might try to make them require Slimefun energy, and then have them jam a radius depending on their tier.
